export type Sector={slug:string;name:string;eyebrow:string;title:string;description:string;thesis:string;signals:string[]};
export const sectors:Sector[]=[
{slug:"manufacturing",name:"Manufacturing",eyebrow:"INDUSTRIAL DEAL FLOW",title:"Distressed Manufacturing Businesses",description:"Masked manufacturing opportunities, asset sales, recapitalizations and operational turnarounds.",thesis:"Manufacturing situations can combine valuable equipment, customer relationships and operating infrastructure with liquidity, leverage or execution pressure.",signals:["Liquidity pressure","Asset-heavy sale","Working-capital stress","Operational turnaround"]},
{slug:"healthcare",name:"Healthcare",eyebrow:"HEALTHCARE SERVICES",title:"Distressed Healthcare Businesses",description:"Healthcare services and operating-company opportunities for qualified strategic and financial buyers.",thesis:"Healthcare transactions require careful screening of operating performance, payer exposure, compliance, ownership and continuity of service.",signals:["Liquidity pressure","Sponsor transition","Strategic sale","Recapitalization"]},
{slug:"technology",name:"Technology",eyebrow:"TECHNOLOGY & SOFTWARE",title:"Distressed Technology Businesses",description:"Software, SaaS and technology situations including strategic sales, recapitalizations and growth-capital pressure.",thesis:"Technology situations may retain attractive recurring revenue, customer contracts and intellectual property despite capital or growth constraints.",signals:["Growth capital need","Strategic alternatives","Recapitalization","IP-led acquisition"]},
{slug:"home-services",name:"Home Services",eyebrow:"SERVICE BUSINESSES",title:"Distressed Home Services Businesses",description:"Residential service platforms and local operators facing capital, leverage or operational constraints.",thesis:"Fragmented local markets can create strategic acquisition opportunities where brand, technician density and recurring customer demand remain valuable.",signals:["Owner transition","Liquidity pressure","Add-on acquisition","Operational turnaround"]},
{slug:"construction",name:"Construction",eyebrow:"CONSTRUCTION",title:"Distressed Construction Businesses",description:"Contractors and construction-related operating companies across special-situations transaction types.",thesis:"Backlog quality, bonding, working capital, equipment and project concentration are central to screening construction situations.",signals:["Working-capital stress","Project concentration","Asset sale","Recapitalization"]},
{slug:"logistics",name:"Logistics",eyebrow:"TRANSPORTATION & LOGISTICS",title:"Distressed Logistics Businesses",description:"Transportation, fleet and logistics opportunities with asset-sale and turnaround potential.",thesis:"Fleet assets, contracted revenue and route density can remain strategically valuable even when leverage or operating performance is under pressure.",signals:["Fleet optimization","Debt pressure","Asset sale","Operational turnaround"]},
{slug:"hospitality",name:"Hospitality",eyebrow:"HOSPITALITY",title:"Distressed Hospitality Businesses",description:"Hospitality operating companies and asset-backed situations for qualified buyers.",thesis:"Hospitality deals can combine operating-company value with real estate, brand, management and capital-structure considerations.",signals:["Debt restructuring","Asset sale","Ownership transition","Liquidity pressure"]},
{slug:"restaurants",name:"Restaurants",eyebrow:"FOOD & BEVERAGE",title:"Distressed Restaurant Businesses",description:"Single-brand and multi-unit restaurant opportunities, recapitalizations and accelerated sales.",thesis:"Unit economics, lease exposure, brand strength and store-level profitability are key screening variables in restaurant situations.",signals:["Covenant pressure","Lease exposure","Recapitalization","Multi-unit sale"]},
{slug:"franchises",name:"Franchises",eyebrow:"FRANCHISE SYSTEMS",title:"Distressed Franchise Businesses",description:"Franchisee groups and operating platforms across special-situations transaction structures.",thesis:"Franchise situations require review of franchisor approvals, territory rights, unit performance, leases and transfer requirements.",signals:["Multi-unit sale","Franchisor consent","Debt pressure","Ownership transition"]},
{slug:"dental-practices",name:"Dental Practices",eyebrow:"DENTAL & DSO",title:"Distressed Dental Practices",description:"Dental practice and group opportunities for qualified healthcare buyers and operators.",thesis:"Provider retention, payer mix, location economics and clinical continuity are important when evaluating dental practice transactions.",signals:["Owner transition","DSO acquisition","Liquidity pressure","Practice consolidation"]},
{slug:"staffing",name:"Staffing",eyebrow:"WORKFORCE SERVICES",title:"Distressed Staffing Businesses",description:"Staffing and workforce-services opportunities shaped by working-capital and customer concentration dynamics.",thesis:"Receivables, payroll funding, customer concentration and recruiter productivity can materially shape staffing transaction risk.",signals:["Working-capital stress","Customer concentration","Recapitalization","Strategic sale"]},
{slug:"retail",name:"Retail",eyebrow:"CONSUMER & RETAIL",title:"Distressed Retail Businesses",description:"Retail operating companies, inventory-led situations and asset-sale opportunities.",thesis:"Inventory quality, lease obligations, channel mix and brand value are central to distressed retail acquisition screening.",signals:["Inventory sale","Lease exposure","Liquidity pressure","Brand acquisition"]}];